package xyz.springabc.domin;
// Generated 2015-11-14 18:40:02 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Node generated by hbm2java
 */
@Entity
@Table(name = "node", catalog = "spring_winds", uniqueConstraints = @UniqueConstraint(columnNames = "name") )
public class Node implements java.io.Serializable {
	private static final long serialVersionUID = 6278423041575132251L;
	private Integer id;
	private Section section;
	private String avatar;
	@NotNull(message="描述不能为空")
	@Size(max=180,message="描述不能超过180个字符")
	private String description;
	private long topicCount=1L;
	@NotNull(message="名称不能为空")
	@Size(max=60,message="名称最多六十个字符")
	private String name;
	private int status;
	private Set<Topic> topics = new HashSet<Topic>(0);
	private Set<Focus> focuses = new HashSet<Focus>(0);

	public Node() {
	}

	public Node(Section section, String name, int status) {
		this.section = section;
		this.name = name;
		this.status = status;
	}

	public Node(Section section, String avatar, String description, String name, int status, Set<Topic> topics,
			Set<Focus> focuses) {
		this.section = section;
		this.avatar = avatar;
		this.description = description;
		this.name = name;
		this.status = status;
		this.topics = topics;
		this.focuses = focuses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "section_id", nullable = false)
	public Section getSection() {
		return this.section;
	}

	public void setSection(Section section) {
		this.section = section;
	}

	@Column(name = "avatar")
	public String getAvatar() {
		return this.avatar;
	}

	public void setAvatar(String avatar) {
		this.avatar = avatar;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}
	
	@Column(name="topic_count")
	public long getTopicCount() {
		return topicCount;
	}

	public void setTopicCount(long topicCount) {
		this.topicCount = topicCount;
	}

	@Column(name = "name", unique = true, nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "status")
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "node")
	public Set<Topic> getTopics() {
		return this.topics;
	}

	public void setTopics(Set<Topic> topics) {
		this.topics = topics;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "node")
	public Set<Focus> getFocuses() {
		return this.focuses;
	}

	public void setFocuses(Set<Focus> focuses) {
		this.focuses = focuses;
	}

}
