package xyz.springabc.domin;
// Generated 2015-11-14 18:40:02 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Property generated by hbm2java
 */
@Entity
@Table(name = "property", catalog = "spring_winds")
public class Property implements java.io.Serializable {
	private static final long serialVersionUID = -5487431171852782954L;
	private Integer id;
	private String keyword;
	private String name;
	private Set<Field> fields = new HashSet<Field>(0);

	public Property() {
	}

	public Property(String keyword) {
		this.keyword = keyword;
	}

	public Property(String keyword, String name, Set<Field> fields) {
		this.keyword = keyword;
		this.name = name;
		this.fields = fields;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "keyword", nullable = false)
	public String getKeyword() {
		return this.keyword;
	}

	public void setKeyword(String keyword) {
		this.keyword = keyword;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "property")
	public Set<Field> getFields() {
		return this.fields;
	}

	public void setFields(Set<Field> fields) {
		this.fields = fields;
	}

}
