package xyz.springabc.domin;
// Generated 2015-11-14 18:40:02 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * Section generated by hbm2java
 */
@Entity
@Table(name = "section", catalog = "spring_winds", uniqueConstraints = @UniqueConstraint(columnNames = "name") )
public class Section implements java.io.Serializable {
	private static final long serialVersionUID = 4338026465342952298L;
	private Integer id;
	@NotNull(message="名称不能为空")
	@Size(max=60,message="名称最多六十个字符")
	private String name;
	private int sort;
	private Set<Node> nodes = new HashSet<Node>(0);

	public Section() {
	}

	public Section(int sort) {
		this.sort = sort;
	}

	public Section(String name, int sort, Set<Node> nodes) {
		this.name = name;
		this.sort = sort;
		this.nodes = nodes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", unique = true)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "sort")
	public int getSort() {
		return this.sort;
	}

	public void setSort(int sort) {
		this.sort = sort;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "section")
	public Set<Node> getNodes() {
		return this.nodes;
	}

	public void setNodes(Set<Node> nodes) {
		this.nodes = nodes;
	}

}
